[package]
name = "hawthoria_bridge"
authors = ["Maddiaa"]
compiler_version = "0.11.1"
type = "contract"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-nr", tag = "master", directory = "aztec" }
